import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider, ThemeProvider } from "@/provider";
import { DevToolsQuery, ModeToggle } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="absolute w-full flex justify-end p-4">
              <ModeToggle />
            </header>
            <main>{children}</main>
          </ThemeProvider>
          <DevToolsQuery />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
